name: test and build gem
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: test + build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x
    - name: rspec
      run: |
        gem install bundler --no-doc
        bundle install
        bundle exec rspec
    - name: build gem
      run: |
        gem build cfhighlander.gemspec